# Generated by Django 5.1 on 2024-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="financeiro_cadastro",
            options={"verbose_name": "Cadastro", "verbose_name_plural": "Cadastro"},
        ),
        migrations.AddField(
            model_name="financeiro_cadastro",
            name="Foto",
            field=models.ImageField(blank=True, upload_to="pictures/%Y/%m"),
        ),
    ]
