# Generated by Django 5.1 on 2024-09-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_financeiro_cadastro_cpf_cnpj_numero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financeiro_cadastro",
            name="Foto",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/%Y/%m"),
        ),
    ]
