# Generated by Django 5.1 on 2024-09-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_alter_financeiro_cadastro_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financeiro_cadastro",
            name="Foto",
        ),
    ]
