# Generated by Django 5.1 on 2024-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_remove_financeiro_cadastro_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("descrição", models.TextField()),
                (
                    "alunos",
                    models.ManyToManyField(
                        related_name="eventos_alunos",
                        to="financeiro.financeiro_cadastro",
                    ),
                ),
                (
                    "professores",
                    models.ManyToManyField(
                        related_name="eventos_professores",
                        to="financeiro.financeiro_cadastro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
    ]
