# Generated by Django 5.1 on 2024-09-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="alunos",
            field=models.ManyToManyField(
                related_name="eventos_alunos",
                to="financeiro.financeiro_cadastro",
                verbose_name="alunos",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="professores",
            field=models.ManyToManyField(
                related_name="eventos_professores",
                to="financeiro.financeiro_cadastro",
                verbose_name="professores",
            ),
        ),
    ]
