# Generated by Django 5.1 on 2024-09-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0007_alter_evento_alunos_alter_evento_professores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="alunos",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="professores",
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("professores", "Professores"),
                            ("alunos", "Alunos"),
                            ("fornecedores", "Fornecedores"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cadastro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeiro.financeiro_cadastro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="participantes",
            field=models.ManyToManyField(
                related_name="eventos", to="financeiro.participante"
            ),
        ),
    ]
