# Generated by Django 5.1 on 2024-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_remove_evento_alunos_remove_evento_professores_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={},
        ),
        migrations.RenameField(
            model_name="evento",
            old_name="descrição",
            new_name="descricao",
        ),
        migrations.RemoveField(
            model_name="participante",
            name="cadastro",
        ),
        migrations.AddField(
            model_name="participante",
            name="cpf",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participante",
            name="nome",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evento",
            name="data",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="evento",
            name="participantes",
            field=models.ManyToManyField(blank=True, to="financeiro.participante"),
        ),
    ]
