# Generated by Django 5.1 on 2024-09-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0009_alter_evento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="participantes_selecionados",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
