# Generated by Django 5.1 on 2024-09-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0011_alter_evento_participantes_selecionados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="participantes_selecionados",
            field=models.TextField(),
        ),
    ]
