# Generated by Django 5.1 on 2024-09-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0014_alter_evento_participantes_selecionados"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="duracao",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
