# Generated by Django 5.1 on 2024-10-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0015_evento_duracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="data",
            field=models.DateField(),
        ),
    ]
