# Generated by Django 5.1 on 2024-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0016_alter_evento_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="financeiro_cadastro",
            name="categoria_de_pagamento",
            field=models.CharField(
                choices=[("Receita", "Receita"), ("Despesa", "Despesa")],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="financeiro_cadastro",
            name="frequencia_de_pagamento",
            field=models.CharField(
                choices=[
                    ("Avulso", "Avulso"),
                    ("Semanal", "Semanal"),
                    ("Mensal", "Mensal"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
