# Generated by Django 5.1 on 2024-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0017_financeiro_cadastro_categoria_de_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financeiro_cadastro",
            name="valor_pago",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
