# Generated by Django 5.1 on 2024-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0023_alter_financeiro_cadastro_data_de_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="recorrencia",
            field=models.CharField(
                choices=[
                    ("Único", "Único"),
                    ("Semanal", "Semanal"),
                    ("Mensal", "Mensal"),
                ],
                default="Único",
                max_length=50,
            ),
        ),
    ]
