# Generated by Django 5.1 on 2024-10-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0024_evento_recorrencia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="recorrencia",
            new_name="recorrência",
        ),
    ]
