# Generated by Django 5.1 on 2024-10-08 21:57

import financeiro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0025_rename_recorrencia_evento_recorrência"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="repeticoes",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[financeiro.models.validar_repeticao],
            ),
        ),
    ]
