# Generated by Django 5.1 on 2024-10-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0026_evento_repeticoes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="repeticoes",
            new_name="repetições",
        ),
    ]
